import { CSSProperties } from 'react';

type Styles = { [key: string]: CSSProperties };

export const styles: Styles = {
  layout: {
    display: 'flex',
    height: '100vh',
    minHeight: 600,
    background: '#f0f0f0',
    borderRadius: 12,
    overflow: 'hidden',
    fontFamily: 'sans-serif',
  },
  sidebar: {
    width: 200,
    background: '#2d3a2e',
    color: '#fff',
    display: 'flex',
    flexDirection: 'column',
    flexShrink: 0,
  },
  brand: {
    padding: '20px 16px 12px',
    borderBottom: '0.5px solid rgba(255,255,255,0.1)',
  },
  brandIcon: {
    width: 28,
    height: 28,
    borderRadius: 6,
    background: '#4a7c5a',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  brandName: { fontSize: 15, fontWeight: 500, color: '#fff' },
  brandSub: { fontSize: 11, color: 'rgba(255,255,255,0.5)', marginTop: 2 },
  nav: { flex: 1, padding: '12px 0' },
  navItem: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    padding: '9px 16px',
    fontSize: 13,
    color: 'rgba(255,255,255,0.65)',
    cursor: 'pointer',
  },
  navItemActive: {
    background: 'rgba(255,255,255,0.1)',
    color: '#fff',
  },
  badge: {
    marginLeft: 'auto',
    background: '#c0392b',
    color: '#fff',
    fontSize: 10,
    fontWeight: 500,
    padding: '1px 6px',
    borderRadius: 99,
  },
  alertItem: {
    margin: '8px 12px',
    background: 'rgba(192,57,43,0.25)',
    border: '0.5px solid rgba(192,57,43,0.5)',
    borderRadius: 8,
    padding: '10px 12px',
  },
  alertItemTitle: { fontSize: 11, fontWeight: 500, color: '#f5a09a' },
  alertItemSub: { fontSize: 11, color: 'rgba(255,255,255,0.5)', marginTop: 2 },
  sidebarBottom: {
    padding: '12px 16px 16px',
    borderTop: '0.5px solid rgba(255,255,255,0.1)',
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    marginTop: 'auto',
  },
  avatar: {
    width: 30,
    height: 30,
    borderRadius: '50%',
    background: '#4a7c5a',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 11,
    fontWeight: 500,
    color: '#fff',
    flexShrink: 0,
  },
  sidebarUserName: { fontSize: 12, color: '#fff', fontWeight: 500 },
  sidebarUserRole: { fontSize: 11, color: 'rgba(255,255,255,0.45)' },
  main: { flex: 1, display: 'flex', flexDirection: 'column', overflow: 'auto' },
  topbar: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '18px 24px 12px',
    background: '#fff',
    borderBottom: '0.5px solid #e5e5e5',
  },
  pageTitle: { fontSize: 18, fontWeight: 500, color: '#111' },
  pageSub: { fontSize: 12, color: '#888', marginTop: 2 },
  topbarRight: { display: 'flex', alignItems: 'center', gap: 10 },
  exportBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    padding: '6px 12px',
    border: '0.5px solid #ddd',
    borderRadius: 6,
    fontSize: 12,
    color: '#111',
    background: '#fff',
    cursor: 'pointer',
  },
  adminAvatar: {
    width: 30,
    height: 30,
    borderRadius: '50%',
    background: '#c0392b',
    color: '#fff',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 11,
    fontWeight: 500,
  },
  content: {
    padding: '20px 24px',
    display: 'flex',
    flexDirection: 'column',
    gap: 20,
  },
  statsRow: { display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: 14 },
  statCard: {
    background: '#fff',
    border: '0.5px solid #e5e5e5',
    borderRadius: 12,
    padding: 16,
  },
  statCardTop: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  statIcon: {
    width: 32,
    height: 32,
    borderRadius: 8,
    background: '#f5f5f5',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  trendUp: {
    fontSize: 11,
    display: 'flex',
    alignItems: 'center',
    gap: 3,
    color: '#2d7a4a',
  },
  trendWarn: {
    fontSize: 11,
    display: 'flex',
    alignItems: 'center',
    gap: 3,
    color: '#c0392b',
  },
  statNum: { fontSize: 24, fontWeight: 500, color: '#111' },
  statLabel: { fontSize: 12, fontWeight: 500, color: '#111', marginTop: 2 },
  statSub: { fontSize: 11, color: '#888', marginTop: 1 },
  bottomRow: { display: 'grid', gridTemplateColumns: '1fr 1.8fr', gap: 14 },
  panel: {
    background: '#fff',
    border: '0.5px solid #e5e5e5',
    borderRadius: 12,
    padding: 16,
  },
  panelHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  panelTitle: {
    fontSize: 13,
    fontWeight: 500,
    color: '#111',
    display: 'flex',
    alignItems: 'center',
    gap: 6,
  },
  panelLink: { fontSize: 12, color: '#888', textDecoration: 'none' },
  stockRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '10px 0',
    borderBottom: '0.5px solid #e5e5e5',
  },
  stockName: { fontSize: 13, fontWeight: 500, color: '#111' },
  stockCat: { fontSize: 11, color: '#888', marginTop: 2 },
  badgeLow: {
    fontSize: 11,
    color: '#b05e1a',
    background: '#faeeda',
    padding: '2px 8px',
    borderRadius: 99,
  },
  badgeEmpty: {
    fontSize: 11,
    color: '#c0392b',
    background: '#fcebeb',
    padding: '2px 8px',
    borderRadius: 99,
  },
  articleRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    padding: '8px 0',
    borderBottom: '0.5px solid #e5e5e5',
  },
  artNum: { fontSize: 13, color: '#888', width: 16, flexShrink: 0 },
  artInfo: { flex: 1, minWidth: 0 },
  artTitle: {
    fontSize: 13,
    fontWeight: 500,
    color: '#111',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  artMeta: { fontSize: 11, color: '#888', marginTop: 2 },
  artStats: { display: 'flex', alignItems: 'center', gap: 12, flexShrink: 0 },
  artStat: {
    display: 'flex',
    alignItems: 'center',
    gap: 4,
    fontSize: 12,
    color: '#888',
  },
};
