ARG NODE_VERSION=24-alpine
FROM node:${NODE_VERSION}

RUN npm install -g pnpm

WORKDIR /app

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

COPY prisma/ ./prisma/
COPY prisma.config.ts ./