services:
  # migrate database (using supabase so just inject the .env)
  migrate:
    image: 'wilson23001/wastranusa-migrate:main'
    env_file:
      - ../../.env
    command: pnpm prisma migrate deploy

  app:
    image: 'wilson23001/wastranusa:main'
    depends_on:
      migrate:
        condition: service_completed_successfully
    # change port to match with server setup
    ports:
      - '3000:3000'
    env_file:
      - ../../.env
