name: WastraNusa Development Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_DEV_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_DEV_PROJECT_ID }}

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  Deployment-Development:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
